Create controller view
yuzesu/chat-space pull request #3
Opened 2019-04-13 07:31 UTC by yuzesu

2019-04-13 07:33 UTC, yuzesu commented
messageコントローラの作成及び仮置きのviewファイルを作成しました。
ご確認よろしくお願いいたします

2019-04-13 07:50 UTC, kuroko918 commented on README.md
> +サービス行う際に必要なデータベースを作る必要があるから
このREADMEはDB設計や、このアプリ全体に関する事項について記述するところです！
WHAT、WHYはプルリクの表題に書きましょう！

2019-04-13 07:50 UTC, kuroko918 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
integer型だとforeign_keyによる外部キー制約が効かないので、references型に変更しましょう！
他のところも変更お願いします！

2019-04-13 08:16 UTC, yuzesu commented
readmeを修正しました。

2019-04-13 08:44 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +%body
bodyタグはapplication.htmlに書いてあるかと思いますので、消しておきましょう！

2019-04-14 09:16 UTC, yuzesu commented on app/views/messages/index.html.haml
> +%body
%bodyは消しました。
他に訂正するべき箇所も教えて頂きたいです。

2019-04-14 09:19 UTC, hiroki5123 commented
#1 をmasterにマージしてください！

2019-04-14 09:21 UTC, ghost requested changes

2019-04-14 09:21 UTC, hiroki5123 commented on app/assets/stylesheets/messages.scss
> +      &__name1{
なんでname1とかname2っていう名前にしているんでしょうか・・・？
nameで定義して、html側もnameにすればいいと思うのですが。。

2019-04-14 09:21 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +        %p.chatspace__side__bottom__name1 sample1グループ
ここname1とかにしないでnameにして、scssの方でnameにすればいいと思います。

2019-04-14 09:21 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +%body
こちら削除されてないので削除してください

2019-04-14 09:21 UTC, hiroki5123 commented
画面のキャプチャをこちらに添付してください。

2019-04-14 09:45 UTC, closed without merging