Create controller view
yuzesu/chat-space pull request #4
Opened 2019-04-14 09:50 UTC by yuzesu

Pushができなくなったので一旦リモートを消しました。
ご迷惑をおかけいて申し訳ないです。

2019-04-14 09:59 UTC, yuzesu commented
![Uploading スクリーンショット 2019-04-14 18.58.26.png…]()

2019-04-14 10:08 UTC, hiroki5123 commented
画像が見れないので再度貼ってください

2019-04-14 10:09 UTC, yuzesu commented
<img width="1680" alt="スクリーンショット 2019-04-14 18 58 26" src="https://user-images.githubusercontent.com/46101371/56091349-cca06c80-5ee8-11e9-908a-b79fc02540d1.png">

2019-04-14 10:09 UTC, ghost requested changes

2019-04-14 10:09 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +      %p.chatspace__main__bottom__top1
こちらもtop1とかになってるので修正をお願い致します。

2019-04-14 10:09 UTC, hiroki5123 commented on app/assets/stylesheets/messages.scss
> +      &__top1{
こちらも修正をお願い致します。

2019-04-14 10:33 UTC, yuzesu commented
ご指摘いただきました箇所を修正いたしました。

2019-04-14 10:35 UTC, hiroki5123 commented
画像を見た所、見本とかなり差があるように感じます。
サイドバーのグループ名の下にメッセージ内容を仮置きで表示してください。

また、送信ボタンの文字の色も違いますし、テキストフォームの大きさ、そして画像を選択するときのアイコンの位置も異なっておりますので、修正をお願い致します。

2019-04-14 10:45 UTC, yuzesu commented
承知いたしました。
適宜修正したのちにお送りいたします。

2019-04-16 22:11 UTC, yuzesu commented
<img width="1680" alt="スクリーンショット 2019-04-17 7 10 41" src="https://user-images.githubusercontent.com/46101371/56247530-0a1b1a80-60e0-11e9-9116-4252ee97ad87.png">

2019-04-17 02:08 UTC, shingoteshima commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット直しましょう。

2019-04-17 02:08 UTC, shingoteshima commented on app/views/layouts/mailer.html.haml
> +!!!
mailer系のファイルは今回仕様しないので削除してしまって大丈夫です。

2019-04-17 09:04 UTC, yuzesu commented
ご指摘の箇所を修正いたしました。

2019-04-17 09:06 UTC, TOMARUMARU approved these changes
LGTM

2019-04-17 09:06 UTC, yuzesu commented
ありがとうございます。

2019-04-17 09:08 UTC, merged